//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication_testWCF.ServiceReference_webservice {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondObject", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BondObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondTermField;
        
        private System.DateTime BondEffectiveFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApplication_testWCF.ServiceReference_webservice.ArrayOfString BondlistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BondNumber {
            get {
                return this.BondNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BondNumberField, value) != true)) {
                    this.BondNumberField = value;
                    this.RaisePropertyChanged("BondNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BondName {
            get {
                return this.BondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BondNameField, value) != true)) {
                    this.BondNameField = value;
                    this.RaisePropertyChanged("BondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BondLimit {
            get {
                return this.BondLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.BondLimitField, value) != true)) {
                    this.BondLimitField = value;
                    this.RaisePropertyChanged("BondLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BondTerm {
            get {
                return this.BondTermField;
            }
            set {
                if ((object.ReferenceEquals(this.BondTermField, value) != true)) {
                    this.BondTermField = value;
                    this.RaisePropertyChanged("BondTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime BondEffectiveFrom {
            get {
                return this.BondEffectiveFromField;
            }
            set {
                if ((this.BondEffectiveFromField.Equals(value) != true)) {
                    this.BondEffectiveFromField = value;
                    this.RaisePropertyChanged("BondEffectiveFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.ArrayOfString Bondlist {
            get {
                return this.BondlistField;
            }
            set {
                if ((object.ReferenceEquals(this.BondlistField, value) != true)) {
                    this.BondlistField = value;
                    this.RaisePropertyChanged("Bondlist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_webservice.SampleWebServiceSoap")]
    public interface SampleWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        int Multiply(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Multiply", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int num1, int num2);
        
        // CODEGEN: Generating message contract since element name bondNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveBond", ReplyAction="*")]
        ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondResponse RetrieveBond(ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetrieveBond", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondResponse> RetrieveBondAsync(ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequest request);
        
        // CODEGEN: Generating message contract since element name accountNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBondsForAccount", ReplyAction="*")]
        ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountResponse GetBondsForAccount(ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBondsForAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountResponse> GetBondsForAccountAsync(ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequest request);
        
        // CODEGEN: Generating message contract since element name bondNumber from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValidBond", ReplyAction="*")]
        ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondResponse IsValidBond(ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsValidBond", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondResponse> IsValidBondAsync(ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveBond", ReplyAction="*")]
        ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondResponse SaveBond(ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveBond", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondResponse> SaveBondAsync(ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveBondRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveBond", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequestBody Body;
        
        public RetrieveBondRequest() {
        }
        
        public RetrieveBondRequest(ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveBondRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bondNumber;
        
        public RetrieveBondRequestBody() {
        }
        
        public RetrieveBondRequestBody(string bondNumber) {
            this.bondNumber = bondNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RetrieveBondResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RetrieveBondResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondResponseBody Body;
        
        public RetrieveBondResponse() {
        }
        
        public RetrieveBondResponse(ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RetrieveBondResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.BondObject RetrieveBondResult;
        
        public RetrieveBondResponseBody() {
        }
        
        public RetrieveBondResponseBody(ConsoleApplication_testWCF.ServiceReference_webservice.BondObject RetrieveBondResult) {
            this.RetrieveBondResult = RetrieveBondResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondsForAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondsForAccount", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequestBody Body;
        
        public GetBondsForAccountRequest() {
        }
        
        public GetBondsForAccountRequest(ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBondsForAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string accountNumber;
        
        public GetBondsForAccountRequestBody() {
        }
        
        public GetBondsForAccountRequestBody(string accountNumber) {
            this.accountNumber = accountNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBondsForAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBondsForAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountResponseBody Body;
        
        public GetBondsForAccountResponse() {
        }
        
        public GetBondsForAccountResponse(ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBondsForAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.BondObject[] GetBondsForAccountResult;
        
        public GetBondsForAccountResponseBody() {
        }
        
        public GetBondsForAccountResponseBody(ConsoleApplication_testWCF.ServiceReference_webservice.BondObject[] GetBondsForAccountResult) {
            this.GetBondsForAccountResult = GetBondsForAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidBondRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidBond", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequestBody Body;
        
        public IsValidBondRequest() {
        }
        
        public IsValidBondRequest(ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsValidBondRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.ArrayOfString bondNumber;
        
        public IsValidBondRequestBody() {
        }
        
        public IsValidBondRequestBody(ConsoleApplication_testWCF.ServiceReference_webservice.ArrayOfString bondNumber) {
            this.bondNumber = bondNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsValidBondResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsValidBondResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondResponseBody Body;
        
        public IsValidBondResponse() {
        }
        
        public IsValidBondResponse(ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsValidBondResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsValidBondResult;
        
        public IsValidBondResponseBody() {
        }
        
        public IsValidBondResponseBody(bool IsValidBondResult) {
            this.IsValidBondResult = IsValidBondResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveBondRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveBond", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequestBody Body;
        
        public SaveBondRequest() {
        }
        
        public SaveBondRequest(ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveBondRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.BondObject bond;
        
        public SaveBondRequestBody() {
        }
        
        public SaveBondRequestBody(ConsoleApplication_testWCF.ServiceReference_webservice.BondObject bond) {
            this.bond = bond;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveBondResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveBondResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondResponseBody Body;
        
        public SaveBondResponse() {
        }
        
        public SaveBondResponse(ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveBondResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_webservice.BondObject bond;
        
        public SaveBondResponseBody() {
        }
        
        public SaveBondResponseBody(ConsoleApplication_testWCF.ServiceReference_webservice.BondObject bond) {
            this.bond = bond;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SampleWebServiceSoapChannel : ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleWebServiceSoapClient : System.ServiceModel.ClientBase<ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap>, ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap {
        
        public SampleWebServiceSoapClient() {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int num1, int num2) {
            return base.Channel.Add(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int num1, int num2) {
            return base.Channel.AddAsync(num1, num2);
        }
        
        public int Multiply(int num1, int num2) {
            return base.Channel.Multiply(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int num1, int num2) {
            return base.Channel.MultiplyAsync(num1, num2);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondResponse ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap.RetrieveBond(ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequest request) {
            return base.Channel.RetrieveBond(request);
        }
        
        public ConsoleApplication_testWCF.ServiceReference_webservice.BondObject RetrieveBond(string bondNumber) {
            ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequest inValue = new ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequest();
            inValue.Body = new ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequestBody();
            inValue.Body.bondNumber = bondNumber;
            ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondResponse retVal = ((ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap)(this)).RetrieveBond(inValue);
            return retVal.Body.RetrieveBondResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondResponse> ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap.RetrieveBondAsync(ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequest request) {
            return base.Channel.RetrieveBondAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondResponse> RetrieveBondAsync(string bondNumber) {
            ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequest inValue = new ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequest();
            inValue.Body = new ConsoleApplication_testWCF.ServiceReference_webservice.RetrieveBondRequestBody();
            inValue.Body.bondNumber = bondNumber;
            return ((ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap)(this)).RetrieveBondAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountResponse ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap.GetBondsForAccount(ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequest request) {
            return base.Channel.GetBondsForAccount(request);
        }
        
        public ConsoleApplication_testWCF.ServiceReference_webservice.BondObject[] GetBondsForAccount(string accountNumber) {
            ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequest inValue = new ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequest();
            inValue.Body = new ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequestBody();
            inValue.Body.accountNumber = accountNumber;
            ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountResponse retVal = ((ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap)(this)).GetBondsForAccount(inValue);
            return retVal.Body.GetBondsForAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountResponse> ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap.GetBondsForAccountAsync(ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequest request) {
            return base.Channel.GetBondsForAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountResponse> GetBondsForAccountAsync(string accountNumber) {
            ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequest inValue = new ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequest();
            inValue.Body = new ConsoleApplication_testWCF.ServiceReference_webservice.GetBondsForAccountRequestBody();
            inValue.Body.accountNumber = accountNumber;
            return ((ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap)(this)).GetBondsForAccountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondResponse ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap.IsValidBond(ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequest request) {
            return base.Channel.IsValidBond(request);
        }
        
        public bool IsValidBond(ConsoleApplication_testWCF.ServiceReference_webservice.ArrayOfString bondNumber) {
            ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequest inValue = new ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequest();
            inValue.Body = new ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequestBody();
            inValue.Body.bondNumber = bondNumber;
            ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondResponse retVal = ((ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap)(this)).IsValidBond(inValue);
            return retVal.Body.IsValidBondResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondResponse> ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap.IsValidBondAsync(ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequest request) {
            return base.Channel.IsValidBondAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondResponse> IsValidBondAsync(ConsoleApplication_testWCF.ServiceReference_webservice.ArrayOfString bondNumber) {
            ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequest inValue = new ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequest();
            inValue.Body = new ConsoleApplication_testWCF.ServiceReference_webservice.IsValidBondRequestBody();
            inValue.Body.bondNumber = bondNumber;
            return ((ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap)(this)).IsValidBondAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondResponse ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap.SaveBond(ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequest request) {
            return base.Channel.SaveBond(request);
        }
        
        public void SaveBond(ref ConsoleApplication_testWCF.ServiceReference_webservice.BondObject bond) {
            ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequest inValue = new ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequest();
            inValue.Body = new ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequestBody();
            inValue.Body.bond = bond;
            ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondResponse retVal = ((ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap)(this)).SaveBond(inValue);
            bond = retVal.Body.bond;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondResponse> ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap.SaveBondAsync(ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequest request) {
            return base.Channel.SaveBondAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondResponse> SaveBondAsync(ConsoleApplication_testWCF.ServiceReference_webservice.BondObject bond) {
            ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequest inValue = new ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequest();
            inValue.Body = new ConsoleApplication_testWCF.ServiceReference_webservice.SaveBondRequestBody();
            inValue.Body.bond = bond;
            return ((ConsoleApplication_testWCF.ServiceReference_webservice.SampleWebServiceSoap)(this)).SaveBondAsync(inValue);
        }
    }
}
