//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication_testWCF.ServiceReference_wcfServiceHost {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BondObject", Namespace="http://schemas.datacontract.org/2004/07/DataContract.Entities")]
    [System.SerializableAttribute()]
    public partial class BondObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BondEffectiveFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondLimitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BondTermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] BondlistField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BondEffectiveFrom {
            get {
                return this.BondEffectiveFromField;
            }
            set {
                if ((this.BondEffectiveFromField.Equals(value) != true)) {
                    this.BondEffectiveFromField = value;
                    this.RaisePropertyChanged("BondEffectiveFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BondLimit {
            get {
                return this.BondLimitField;
            }
            set {
                if ((object.ReferenceEquals(this.BondLimitField, value) != true)) {
                    this.BondLimitField = value;
                    this.RaisePropertyChanged("BondLimit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BondName {
            get {
                return this.BondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BondNameField, value) != true)) {
                    this.BondNameField = value;
                    this.RaisePropertyChanged("BondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BondNumber {
            get {
                return this.BondNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BondNumberField, value) != true)) {
                    this.BondNumberField = value;
                    this.RaisePropertyChanged("BondNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BondTerm {
            get {
                return this.BondTermField;
            }
            set {
                if ((object.ReferenceEquals(this.BondTermField, value) != true)) {
                    this.BondTermField = value;
                    this.RaisePropertyChanged("BondTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Bondlist {
            get {
                return this.BondlistField;
            }
            set {
                if ((object.ReferenceEquals(this.BondlistField, value) != true)) {
                    this.BondlistField = value;
                    this.RaisePropertyChanged("Bondlist");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_wcfServiceHost.ISampleWebService")]
    public interface ISampleWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/Add", ReplyAction="http://tempuri.org/ISampleWebService/AddResponse")]
        int Add(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/Add", ReplyAction="http://tempuri.org/ISampleWebService/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/Multiply", ReplyAction="http://tempuri.org/ISampleWebService/MultiplyResponse")]
        int Multiply(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/Multiply", ReplyAction="http://tempuri.org/ISampleWebService/MultiplyResponse")]
        System.Threading.Tasks.Task<int> MultiplyAsync(int num1, int num2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/RetrieveBond", ReplyAction="http://tempuri.org/ISampleWebService/RetrieveBondResponse")]
        ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject RetrieveBond(string bondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/RetrieveBond", ReplyAction="http://tempuri.org/ISampleWebService/RetrieveBondResponse")]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject> RetrieveBondAsync(string bondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/GetBondsForAccount", ReplyAction="http://tempuri.org/ISampleWebService/GetBondsForAccountResponse")]
        ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject[] GetBondsForAccount(string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/GetBondsForAccount", ReplyAction="http://tempuri.org/ISampleWebService/GetBondsForAccountResponse")]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject[]> GetBondsForAccountAsync(string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/IsValidBond", ReplyAction="http://tempuri.org/ISampleWebService/IsValidBondResponse")]
        bool IsValidBond(string[] bondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/IsValidBond", ReplyAction="http://tempuri.org/ISampleWebService/IsValidBondResponse")]
        System.Threading.Tasks.Task<bool> IsValidBondAsync(string[] bondNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/SaveBond", ReplyAction="http://tempuri.org/ISampleWebService/SaveBondResponse")]
        ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondResponse SaveBond(ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISampleWebService/SaveBond", ReplyAction="http://tempuri.org/ISampleWebService/SaveBondResponse")]
        System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondResponse> SaveBondAsync(ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveBond", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveBondRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject bond;
        
        public SaveBondRequest() {
        }
        
        public SaveBondRequest(ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject bond) {
            this.bond = bond;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaveBondResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SaveBondResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject bond;
        
        public SaveBondResponse() {
        }
        
        public SaveBondResponse(ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject bond) {
            this.bond = bond;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISampleWebServiceChannel : ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.ISampleWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SampleWebServiceClient : System.ServiceModel.ClientBase<ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.ISampleWebService>, ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.ISampleWebService {
        
        public SampleWebServiceClient() {
        }
        
        public SampleWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SampleWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SampleWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int num1, int num2) {
            return base.Channel.Add(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int num1, int num2) {
            return base.Channel.AddAsync(num1, num2);
        }
        
        public int Multiply(int num1, int num2) {
            return base.Channel.Multiply(num1, num2);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyAsync(int num1, int num2) {
            return base.Channel.MultiplyAsync(num1, num2);
        }
        
        public ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject RetrieveBond(string bondNumber) {
            return base.Channel.RetrieveBond(bondNumber);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject> RetrieveBondAsync(string bondNumber) {
            return base.Channel.RetrieveBondAsync(bondNumber);
        }
        
        public ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject[] GetBondsForAccount(string accountNumber) {
            return base.Channel.GetBondsForAccount(accountNumber);
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject[]> GetBondsForAccountAsync(string accountNumber) {
            return base.Channel.GetBondsForAccountAsync(accountNumber);
        }
        
        public bool IsValidBond(string[] bondNumber) {
            return base.Channel.IsValidBond(bondNumber);
        }
        
        public System.Threading.Tasks.Task<bool> IsValidBondAsync(string[] bondNumber) {
            return base.Channel.IsValidBondAsync(bondNumber);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondResponse ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.ISampleWebService.SaveBond(ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondRequest request) {
            return base.Channel.SaveBond(request);
        }
        
        public void SaveBond(ref ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.BondObject bond) {
            ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondRequest inValue = new ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondRequest();
            inValue.bond = bond;
            ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondResponse retVal = ((ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.ISampleWebService)(this)).SaveBond(inValue);
            bond = retVal.bond;
        }
        
        public System.Threading.Tasks.Task<ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondResponse> SaveBondAsync(ConsoleApplication_testWCF.ServiceReference_wcfServiceHost.SaveBondRequest request) {
            return base.Channel.SaveBondAsync(request);
        }
    }
}
